config/routes.rb
NkV1::Application.routes.draw do

 root 'static_pages#launch'
 get "/demo" => "static_pages#home", via: "get"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
   mount Ckeditor::Engine => '/ckeditor'
   if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end
   resources :contact_forms
 devise_for :users , :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'} 
 match '/del_google_calendar_alert', to:'set_alerts#remove_google_calendar_alert', via: 'get'
 match '/del_fb_alert', to:'set_alerts#remove_fb_alert', via: 'delete'
 match '/set_fb_alert', to:'set_alerts#set_fb_alert', via: 'get'
 match '/set_google_calendar_alert', to:'set_alerts#set_google_calendar_alert', via: 'get'
 match '/refresh', to:'refresh#index', via: 'get'
 match '/delfb', to:'push2fb#destroy', via: 'delete'       
 match '/sort', to:'refresh#by_date', via:'get' 
 match '/search', to:'refresh#search', via:'get' 
 match '/myevents', to:'refresh#myevents', via:'get'
 match '/hall', to:'refresh#hallevents', via:'get'
 match '/campus', to:'refresh#campusevents', via:'get'
 match '/approvals', to:'admin#index', via:'get' 
 match '/approve', to:'admin#update', via:'get'                        
 get "users/preferences"

   resources :events do #, shallow: true
      put :favorite, on: :member
        put :followfeed, on: :member
          put :share, on: :member
            put :submit, on: :member
   end
   
   resources :groups, except: [:show, :index]
   resources :campuses do
       resources :groups, only: [:show, :index]      
   end
   resources :users do
     member do
       get :following, :followers
     end
   end
   resources :microposts, :only => [:create, :destroy]
   resources :relationships, :only => [:create, :destroy]

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/new_events', to: 'static_pages#new_events', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/our_works', to: 'static_pages#our_works', via: 'get'
  match '/patnerships', to: 'static_pages#patnerships', via: 'get'
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  
  @campus = Campus.new
    #@title = "Home"
    @categories = Category.all
  end
  
  def new_events
  t = Time.at(params[:created_at].to_i)
     @events = Event.where("updated_at > ?",Time.at(params[:created_at].to_i))
     @user = current_user || User.new
     respond_to do |format|
        format.js
     end
  end
  
  def about
   # @title = "About"
  end
  
  def contact
   # @title = "Contact"
  end
  
  def help
   # @title = "Help"
  end
  
  def faq  
  end
  def tour
  end
  def our_works
  end
  def team
  end
  def partnerships
  end
  def show
     @events = Event.all.reverse
     respond_to do |format|
     format.js
     end
     end
   def launch
     render :layout => false 
   end
      
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_event.html.erb
<title></title>
<div class="alert alert-dismissable alert-warning eventspc">
  <button type="button" class="close" data-dismiss="alert">X</button>
    <table class ="table table-striped table-hover eventspc" style="table-layout: fixed;">
      <tbody>
        <tr>
    <!-=================================first column===========================================->
          <td width="9.5%" class="resp">
            <div class="thumbnail">
              <div class="caption">
                <h4><%= event.reach.name if event.reach.present? %></h4>
                  <p><a class="label label-primary">Bee Score: <%= event.shared_by.count%></a>
                    <% if @user.usershares.include?(event) %>
                    <%= link_to share_event_path(event, type: "undo share"), method: :put ,:class => "btn btn-primary btn-xs tour_3" do %>Un-bee it!
                      <% end %>
                      <% else %>       
                    <%= link_to share_event_path(event, type: "share"), method: :put,:class => "btn btn-primary btn-xs" do %><i class="icon icon-share">Bee it!</i> 
                      <% end %>
                    <% end %></p>
                      <a href="https://twitter.com/intent/tweet" class="twitter-share-button" data-lang="en" data-text="<%=event.title %>" data-hashtags="<%=event.organizer%>" data-url="http://kampusbee.com/events/<%=event.id%>" data-count="none"  data-via="<%=event.venue%>,<%= event.location%>">Tweet</a>
              </div>               
                <% if event.avatar.present?%>
                  <%= image_tag event.avatar.url, size: "160x100"%>
                <% else %>
                  <%= image_tag 'logo1.png', size: "160x100"%>
                <% end %>
            </div>                
  <p class="tour_4"></p>
        </td>
  <!-=========----second column--=============================-------->
    <td class="event_center" width="30%">   
      <div style="word-wrap: break-word;">
        <% if @user.userfavorites.include?(event) %>       
         <%= link_to favorite_event_path(event, type: "unfavorite"),{ method: :put ,title: "unfavorite"} do %>
            <i class="icon icon-star" style="color: rgba(0, 0, 0, 0.74);"></i>
            <% end %>
        <% else %>
         <%= link_to favorite_event_path(event, type: "favorite"), {method: :put,title: "favorite"} do %>
            <i class="icon icon-star-empty" style="color: rgba(0, 0, 0, 0.74);"></i>
            <% end %>
         <% end %>
    
    <%= link_to event.title,event,class: "event_title" %> <br> 
    <i class="fa fa-users"></i> 
     <%=event.organizer%> 
     <button type="button" class="btn btn-primary btn-xs what" data-container="body" data-toggle="popover" data-placement="top" data-content="<%=event.short_description%>" data-original-title="" title=""><div class="tour_6"><i class="icon icon-eye-open"></i> What!?</div></button>
    <table class ="table table-striped table-hover eventspc" style="table-layout: fixed;">
      <tbody>
  <!-==============---Second column table----==============------>
        <tr>    
         <td class="eventrow2"><i class="icon icon-calendar"></i> 
           <%=event.sdatetime.strftime("%d %b %I:%M %p")%> - <%=event.edatetime.strftime("%d %b %I:%M %p")%></td></tr>
        <tr><td class="eventrow2"><i class="icon icon-map-marker"> </i>
            <%=event.venue%>, <%=event.campus.name%>
        </td></tr>
    </tbody></table></td>
    <!-========---Responsive Design Part----======================------>
    <div class="event_resp">
      <div style="word-wrap: break-word;">
         <% if @user.userfavorites.include?(event) %>       
          <%= link_to favorite_event_path(event, type: "unfavorite"),{ method: :put ,title: "unfavorite"} do %><i class="icon icon-star" style="color: rgba(0, 0, 0, 0.74);"></i><% end %>
          <% else %>
          <%= link_to favorite_event_path(event, type: "favorite"), {method: :put,title: "favorite"} do  %><i class="icon icon-star-empty" style="color: rgba(0, 0, 0, 0.74);"></i><% end %>
         <% end %>    
          <%= link_to event.title,event,class: "event_title" %> <br> <i class="fa fa-users"></i>  <%=event.organizer%>
      </div> 
      <div class="thumbnail">
        <div class="caption">
            <h4><i class="icon icon-calendar"> </i> 
            <%=event.sdatetime.strftime("%d %b %I:%M %p")%> - <%=event.edatetime.strftime("%d %b %I:%M %p")%></h4>
            <h4> <i class="icon icon-map-marker"> </i><%=event.venue%>,<%=event.campus.name%></h4>
                <p><a class="label label-primary">Bee Score: <%= event.shared_by.count%></a>
                   <% if @user.usershares.include?(event) %>
              <%= link_to share_event_path(event, type: "undo share"), method: :put ,:class => "btn btn-primary btn-xs tour_3" do %>
             <i class="icon icon-share">Un-bee it!</i>
           <% end %>
        <% else %>
          <%= link_to share_event_path(event, type: "share"), method: :put,:class => "btn btn-primary btn-xs" do %>
           <i class="icon icon-share">Bee it!</i> 
        <% end %>
    <% end %>  
    <button type="button" class="btn btn-primary btn-xs" data-container="body" data-toggle="popover" data-placement="top" data-content="<%=event.short_description%>" data-original-title="" title=""><div class="tour_6"><i class="icon icon-eye-open"></i> What!?</div></button>
    <a href="https://twitter.com/intent/tweet" class="twitter-share-button" data-lang="en" data-text="<%=event.title %>" data-hashtags="<%=event.organizer%>" data-url="http://kampusbee.com/events/<%=event.id%>" data-count="none"  data-via="<%=event.venue%>,<%= event.location%>" >Tweet</a>         
        </p>
          
    </div>
                              
    <%if event.avatar.present?%>
       <%= image_tag event.avatar.url, size: "160x100"%>
    <% else %>
       <%= image_tag 'logo1.png', size: "160x100"%>
     <% end %>

   </div>
           <!-==================- <p>Resposive design ends</p>=======================->
           <!-==============---Third column----==============------> 
  <td class = "aRi" width="20%">          
    <div class="aU5"><span class="aRh"><%=event.sdatetime.strftime("%b") %></span><span class="aRg"><%=event.sdatetime.day %></span><span class="aRj"><%=event.sdatetime.strftime("%a") %></span></div>
      <div class="tour_5"> 
        <div class="thumbnail">       
          <a href="#" class=" btn btn-primary btn-sm" >
            <i class="fa fa-bell-o"> <span class="res">Alerts!</span></i></a>
            <div class="caption">
              <% @push = SetAlert.where(:user_id => @user.id, :event_id => event.id).first_or_initialize %>
              <% if @push.gcpush_id.present? %>
                <%= link_to @push.gcpush_htmllink, class:"btn btn-social-icon btn-xs btn-google-plus" do %> <i class="fa fa-pencil"> </i><% end%>
                <%= link_to del_google_calendar_alert_path(:id => event.id),method: :delete, data: {confirm: 'Are you sure?'},class:"btn btn-social-icon btn-xs btn-google-plus" do %><i class="fa fa-google-plus"> </i><% end%>
                <% else %> 
                <%= link_to set_google_calendar_alert_path(:id => event.id), class:"btn btn-social-icon btn-xs btn-google-plus" do %><i class="fa fa-google-plus"></i><% end%>
              <% end%>
         
              <% if @push.fbpush_id.present? %>
                <%= link_to del_fb_alert_path(:id => event.id), method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-social-icon btn-xs btn-facebook" do %>Delete alert <i class="fa fa-facebook"></i><% end%>
                <% else %>
                <%= link_to set_fb_alert_path(:id => event.id), class:"btn btn-social-icon btn-xs btn-facebook" do %> <i class="fa fa-facebook"></i><% end%>
              <% end%>
    </div>
  </div>                                       
</div>
</td> 
  <!-=================ends======================---------->               
</tr>          
</tbody>
</table>                 
</div>
           

app/views/static_pages/_feed.html.erb
<p> Bee Feed: 
<%= @events.count %> events were created <%=time_ago_in_words(@events[0].created_at) %> ago. 

app/views/static_pages/_group_slider.html.erb
    <div class='col-md-6'>
      <div class="carousel slide media-carousel res" id="media1">
        <div class="carousel-inner">
          <div class="item active">
            <div class="row">
              <div class="col-md-6">
                <a class="thumbnail" href="#"><img alt="" src="http://2.bp.blogspot.com/-H6MAoWN-UIE/TuRwLbHRSWI/AAAAAAAABBk/89iiEulVsyg/s400/Free%2BNature%2BPhoto.jpg"></a>
              </div>          
                  
            </div>
          </div>
          <div class="item">
            <div class="row">
              <div class="col-md-4">
                <a class="thumbnail" href="#"><img alt="" src="http://2.bp.blogspot.com/-H6MAoWN-UIE/TuRwLbHRSWI/AAAAAAAABBk/89iiEulVsyg/s400/Free%2BNature%2BPhoto.jpg"></a>
              </div>                  
            </div>
          </div>
          <div class="item">
            <div class="row">
              <div class="col-md-4">
                <a class="thumbnail" href="#"><img alt="" src="http://placehold.it/150x150"></a>
              </div>          
              <div class="col-md-4">
                <a class="thumbnail" href="#"><img alt="" src="http://placehold.it/150x150"></a>
              </div>
              <div class="col-md-4">
                <a class="thumbnail" href="#"><img alt="" src="http://placehold.it/150x150"></a>
              </div>      
            </div>
          </div>
        </div>
        <a data-slide="prev" href="#media1" class="left carousel-control">‹</a>
        <a data-slide="next" href="#media1" class="right carousel-control">›</a>
      </div>                          
    </div>

app/views/static_pages/_refresh.html.erb
<%= render partial: "static_pages/event", collection: @events %>

app/views/static_pages/_slides.html.erb
<%= image_tag

app/views/static_pages/_tour.html.erb
<title></title>

		<script type="text/javascript">

        if(!(jQuery.Storage.get("tour") == "true")){
        	var config = {
        	    mainTitle: "First time here?!",
        	    saveCookie: true, 
        		steps: [
        		{
					"name" 		: "tour_1",
					"bgcolor"	: "black",
					"color"		: "white",
					"position"	: "TL",
					"text"		: "Want to stay informed about the events happening inside the campus? Well! We bring to you the event management platform that let's you browse through what's hot inside. User can set up event preferences, social alerts and can promote events too. A bee score will be set to each event.",
					"time" 		: 5000
				},
				{
					"name" 		: "tour_2",
					"bgcolor"	: "black",
					"color"		: "white",
					"text"		: "You can check out all active events on campus here. You can tab through! Trending - will have events sorted based on event bee score. Well! What is beescore?",
					"position"	: "BL",
					"time" 		: 5000
				},
				{
					"name" 		: "tour_3",
					"bgcolor"	: "black",
					"color"		: "white",
					"text"		: "Bee it! - Kampusbee's way of promoting an event. It updates beescore. Each promotion by a user, adds on to the bee score",
					"position"	: "BL",
					"time" 		: 5000
				},
				{
					"name" 		: "tour_4",
					"bgcolor"	: "black",
					"color"		: "white",
					"text"		: "Check out the bee score here! If it says '2'-it means two users have promoted this event",
					"position"	: "BL",
					"time" 		: 5000
				},
				{
					"name" 		: "tour_5",
					"bgcolor"	: "black",
					"color"		: "white",
					"text"		: "Set up your social alerts by a single click!",
					"position"	: "BL",
					"time" 		: 5000
				},
				{
					"name" 		: "tour_6",
					"bgcolor"	: "black",
					"color"		: "white",
					"text"		: "Hover over to know about the brief event description. Event tweet! a 140 character long description of the event ",
					"position"	: "BL",
					"time" 		: 5000
				},
				{
					"name" 		: "tour_7",
					"bgcolor"	: "black",
					"color"		: "white",
					"text"		: "Favorite the event by clicking the star!",
					"position"	: "BL",
					"time" 		: 5000
				},
				
				{
					"name" 		: "tour_8",
					"bgcolor"	: "black",
					"color"		: "white",
					"text"		: "Filter and view events as per your choice here!",
					"position"	: "BL",
					"time" 		: 5000
				},
				{
					"name" 		: "tour_9",
					"bgcolor"	: "black",
					"color"		: "white",
					"text"		: "Check out the featured events here! You can even close the events for easy readability.",
					"position"	: "BL",
					"time" 		: 5000
				},
				{
					"name" 		: "tour_10",
					"bgcolor"	: "black",
					"color"		: "white",
					"text"		: "Don't forget to give your feedback! We greatly appreciate it!",
					"position"	: "BL",
					"time" 		: 5000
				}
				]
				
				
				
        	};

        	$.tour.start(config);

        }

        </script>
		

app/views/static_pages/faq.html.erb
    <!-- End: HEADER -->
    <!-- Start: MAIN CONTENT -->
      <div class="container">
        <div class="page-header">
          <h1>Frequently asked questions</h1>
        </div>  
        <div class="row">
          <div class="span10 offset1">
            <div class="accordion" id="faqAccordion">
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq1">
                      <i class="icon-question-sign"></i> How to add events?
                    </a>
                  </h4>
                </div>
                <div id="faq1" class="accordion-body collapse in">
                  <div class="accordion-inner">
                    <p>
                      It's easy. Go to "add events" link on the top navigation bar. Fill in the details and submit. Anyone can submit an event. The events will be submitted for approval though. User will have scores based on the number of events submitted. We are building a system for users where they get special moderation status for their support eventually. 
                    </p>
                  </div>
                </div>
              </div>
               <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq9">
                      <i class="icon-question-sign"></i> Short description of an event?
                     
                    </a>
                  </h4>
                </div>
                <div id="faq9" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                    It's a 140 characters long description of an event - a Event Tweet. This is <b>mandatory</b> for anyone to add an event. We encourge people to come up with something short about the event.
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq2">
                      <i class="icon-question-sign"></i> How Kampusbee is different from any other event management system?
                    </a>
                  </h4>
                </div>
                <div id="faq2" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                  Colleges are our primary focus. We are never gonna move away from that. A user can set up his preferences. He can check out the events based on his preferences at 'my events' tag. We want to provide all event details easily accessible in the event box. You can set up alerts too by a single click. Isn't it different?  
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq3">
                      <i class="icon-question-sign"></i> What is a Bee Score?
                    </a>
                  </h4>
                </div>
                <div id="faq3" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      Bee score is related to number of users promoting an event. "Here user is a promoter". Bee-it is a way to promote the event. Good bee scores means ample activity happening around the event. The score is internal and kampusbee specific. 
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq4">
                      <i class="icon-question-sign"></i> What if the categories/domains/eligibles that I seek are not available in the events page?
                    </a>
                  </h4>
                </div>
                <div id="faq4" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      Write to us about the new categories/domains/eligible. We give you the access to create your own too for the starters.  
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq5">
                      <i class="icon-question-sign"></i> How do you ensure the event details are right?
                    </a>
                  </h4>
                </div>
                <div id="faq5" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      One way is to check out the event by the kampusbee representative. We want to bring down this process further by adding student ambassador network. Work is going on various moderating levels like hall admin, campus admin to ensure this. Stay tuned to become a Hall kingBee, Campus KingBee etc etc. We would like to hear your solution too. <%= link_to "feedback", new_contact_form_path%>
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq6">
                      <i class="icon-question-sign"></i> What are social alerts?
                    </a>
                  </h4>
                </div>
                <div id="faq6" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      You can push events to get notifications through social networking sites. Just by a single click you can add the event into your google calendars and facebook events. They are all set to defaults - <b>accessible and visible only to you</b>.
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq7">
                      <i class="icon-question-sign"></i> I have a better idea. What should I do?
                    </a>
                  </h4>
                </div>
                <div id="faq7" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                    Even we thought ours was a better idea. It's subjective unless we objectify it with facts. Get in touch with us! We are open to ideas <%= link_to "Feedback", new_contact_form_path%>
                    </p>
                  </div>
                </div>
              </div>
              <div class="accordion-group">
                <div class="accordion-heading">
                  <h4>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#faqAccordion" href="#faq8">
                      <i class="icon-question-sign"></i> I couldn't sleep for two days what should I do?
                    </a>
                  </h4>
                </div>
                <div id="faq8" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      We certainly don't have an answer for that. Give us more details may be we will get back to you!
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <!-- End: MAIN CONTENT -->
    <!-- Start: FOOTER -->

app/views/static_pages/home.html.erb
<title>   </title>  
  <script>
    $(window).bind("load", function() {
       $.getScript('<%= asset_path('social.js') %>', function() {});
    });
  </script>                   
    <!--=========================== Start: MAIN CONTENT ========================================-->
  <div class="splash">
    <% if session[:events].present? %>
      <%= link_to "Continue Submission", new_event_path,:type => 'button',:class => 'btn btn-info'%>        
    <% end %>
     <div class="container">   
      <div class="row">    
        <h1 class="tour_1 fontedits" >Thousands of events around your campus. </h1>
        <h4 class="fontedits" > Events that interest you are just a click away!</h4> <br>
        <h5 class="fontedits">Pick up your interests </h5>
    <!---<div class="fb-like-box" data-href="http://www.facebook.com/Kampusbeecom" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div>-->
   <%# render partial: "shared/video" %>
        <%= form_tag refresh_path, :method => :get do %><br>
        <%= render partial: "static_pages/slider" %><br> <br>     
        
        <%=submit_tag "Start exploring",class:"btn btn-primary btn-lg wireframe move fontedits" %>
        <% end %>    
      </div><br><br><br> <br>
    <div class="row">
     <div class="col-lg-7"> 
      <ul class="list_style">
      <li><span class="fa fa-users"></span>Stay notified about latest happenings in and around your campus</li>
      <li><span class="fa fa-envelope"></span>Create events for free. It's supereasy.</li>
      <li><span class="fa fa-lock"></span>Follow users/organizers to check out the events they are attending/organizing</li>
      <li><span class="fa fa-envelope"></span>Push alerts to google calendar and facebook just by a single click! Stay notified!</li>      
      <li><span class="fa fa-envelope"></span>Subscribe to our newsletter to get to know about latest events catalogue. We don't spam.</li>
      <li><span class="fa fa-comments"></span>Easy signup using social network logins</li>                      
      </ul>
    </div>    
    <div class="col-lg-5 ">  
      <div class="well wellopac">
      <h1 class="fontedits">Start here </h1>
      <h3>Check out the events happening in your campus</h3>  
        <%=collection_select nil, :campus_id, Campus.all, :short_name, :name,{:prompt => 'Please select your campus'},{:onchange => "document.location = '/campuses/' + this.value", :class => "form-control"} %><br>
      <h5>Campus not available? Add here.</h5>
        <%= form_for @campus do |f| %>
      <div class="row">
      <div class="col-lg-8 ">
        <%= f.text_field :name, :placeholder =>'Submit your campus',class: 'form-control' %>
        <p>Ex: Indian Institute of Technology Kharagpur, Vellore Institute of Technology</p>
      </div>
      <div class="col-lg-4 ">
        <%= f.text_field :short_name, :placeholder =>'Short name',class: 'form-control' %><br>
       <p>Ex: IITKGP, VIT</p>
      </div>
      </div>     
        <%= f.submit "Submit", class: "btn btn-sm btn-primary center" %>          
    <%end%>                                                        
  </div>
 </div>
</div> 
</div>
    </div>
        <!--======================= Center stufff===============-->
<div class="container">
	<div class="row">

    	<div class="col-xs-12 col-sm-6 col-lg-4">
			<div class="box">							
				<div class="icon">
					<div class="image"><i class="fa fa-thumbs-o-up"></i></div>
					<div class="info">
						<h3 class="title">Creating events is free</h3>
						<p>
						  You can create event pages for any event in no time. It's free and supereasy. 
						</p>
						<div>
						<a class="btn btn-primary btn-md" href="<%=new_event_path%>">Create an Event</a>
							
						</div>
					</div>
				</div>
				<div class="space"></div>
			</div> 
		</div>
			
     <div class="col-xs-12 col-sm-6 col-lg-4">
			<div class="box">							
				<div class="icon">
					<div class="image"><i class="fa fa-flag"></i></div>
					<div class="info">
						<h3 class="title">Participate, debate, discuss and share actively</h3>
    					<p>
							Earn BeeScores through active discussions, polls, surveys, feedbacks, suggestions etc. Redeem scores to unlock discount vouchers.  
						</p>
						<div class="more">
							<a href="#" title="Title Link">
								Read more <i class="fa fa-angle-double-right"></i>
							</a>
						</div>
					</div>
				</div>
				<div class="space"></div>
			</div> 
		</div>
			
        <div class="col-xs-12 col-sm-6 col-lg-4">
			<div class="box">							
				<div class="icon">
					<div class="image"><i class="fa fa-users"></i></div>
					<div class="info">
						<h3 class="title">Build networks inside your campuses</h3>
    					<p>
							Create groups inside your campuses. Build activity. 
						</p>
						<div class="more">
							<a href="#" title="Title Link">
								Read More <i class="fa fa-angle-double-right"></i>
							</a>
						</div>
					</div>
				</div>
				<div class="space"></div>
			</div> 
		</div>		    
		
	</div>
</div>

    <!-- ==================================================================================== -->
    <!-- <div class="col-lg-4 col-lg-offset-4">
            <input type="search" id="container-search" value="" class="form-control" placeholder="Search...">
        </div>--> 
        
  <div class="featurette" id="sec2">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1>Amazing Features</h1>
        </div>
      </div>
    <div class="row">
      <div class="col-md-2 col-md-offset-2 text-center">
        <div class="featurette-item">
          <i class="icon-bell"></i>
          <h4>Alerts</h4>
          <p>Setting up social alerts is a piece of cake</p>
        </div>
      </div>
      <div class="col-md-2 text-center">
        <div class="featurette-item">
          <i class="icon-star"></i>
          <h4>Events</h4>
          <p>Now creating events is free and super-easy</p>
        </div>
      </div>
      <div class="col-md-2 text-center">
        <div class="featurette-item">
          <i class="fa fa-users"></i>
          <h4>Network Groups</h4>
          <p>Follow other users/organisers. Create/Join groups. Have fun!</p>
        </div>
      </div>
      <div class="col-md-2 text-center">
        <div class="featurette-item">
          <i class="icon-pencil"></i>
          <h4>Interests</h4>
          <p>Set up your interests. Get notified about latest events as per your preferences.</p>
        </div>
      </div>
    </div>
  </div>
</div><br>
<div class="container">
  <%# render partial: "static_pages/group_slider" %><br>
  <%# render partial: "shared/group", collection: @campus_groups%>   
</div>
    <!-- End: MAIN CONTENT -->

app/views/static_pages/new_events.js.erb
created_at = <%= Time.now.to_i %>;
$("#sixth").prepend("<%= escape_javascript(render partial:'static_pages/feed', collection: @events) %>"); 