config/routes.rb
NkV1::Application.routes.draw do

 root 'static_pages#launch'
 get "/demo" => "static_pages#home", via: "get"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
   mount Ckeditor::Engine => '/ckeditor'
   if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end
   resources :contact_forms
 devise_for :users , :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'} 
 match '/del_google_calendar_alert', to:'set_alerts#remove_google_calendar_alert', via: 'get'
 match '/del_fb_alert', to:'set_alerts#remove_fb_alert', via: 'delete'
 match '/set_fb_alert', to:'set_alerts#set_fb_alert', via: 'get'
 match '/set_google_calendar_alert', to:'set_alerts#set_google_calendar_alert', via: 'get'
 match '/refresh', to:'refresh#index', via: 'get'
 match '/delfb', to:'push2fb#destroy', via: 'delete'       
 match '/sort', to:'refresh#by_date', via:'get' 
 match '/search', to:'refresh#search', via:'get' 
 match '/myevents', to:'refresh#myevents', via:'get'
 match '/hall', to:'refresh#hallevents', via:'get'
 match '/campus', to:'refresh#campusevents', via:'get'
 match '/approvals', to:'admin#index', via:'get' 
 match '/approve', to:'admin#update', via:'get'                        
 get "users/preferences"

   resources :events do #, shallow: true
      put :favorite, on: :member
        put :followfeed, on: :member
          put :share, on: :member
            put :submit, on: :member
   end
   
   resources :groups, except: [:show, :index]
   resources :campuses do
       resources :groups, only: [:show, :index]      
   end
   resources :users do
     member do
       get :following, :followers
     end
   end
   resources :microposts, :only => [:create, :destroy]
   resources :relationships, :only => [:create, :destroy]

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/new_events', to: 'static_pages#new_events', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/our_works', to: 'static_pages#our_works', via: 'get'
  match '/patnerships', to: 'static_pages#patnerships', via: 'get'
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
  <div class="panel-heading" id="error_explanation">
      <h4 ><%= pluralize(object.errors.count, "error") %>
          prohibited this user from being saved: </h4>
          </div>
 <div class="panel-body">
 <p> There were problems with the following fields:</p>
    <ul class="error">
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
<div class="col-lg-5 col-lg-offset-4">
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
   </div>
<% end %>
 

app/views/shared/_group.html.erb
<div class ="row">

<div class="col-lg-8"><label for="img1"><img class="img-responsive" src="http://2.bp.blogspot.com/-H6MAoWN-UIE/TuRwLbHRSWI/AAAAAAAABBk/89iiEulVsyg/s400/Free%2BNature%2BPhoto.jpg" /></label><div class="imgbox"><input type="checkbox" checked="checked" id="img1" name="img1" value="0"  /><p class="imgtext"><%=group.name%></p></div></div>

</div>

app/views/shared/_groups.html.erb
<div class="container center">
      <%= form_tag refresh_path, :method => :get do %>
	<div class="row">
	
		<div class="col-md-2 col-sm-4 col-xs-6"><label for="img1"><img class="img-responsive" src="http://2.bp.blogspot.com/-H6MAoWN-UIE/TuRwLbHRSWI/AAAAAAAABBk/89iiEulVsyg/s400/Free%2BNature%2BPhoto.jpg" /></label><div class="imgbox"><input type="checkbox" checked="checked" id="img1" name="img1" value="0"  /><p class="imgtext">Sports Society</p></div></div>
        <div class="col-md-2 col-sm-4 col-xs-6"><label for="img2"><img class="img-responsive" src="http://www.virginia.org/uploadedImages/virginiaorg/Images/OrgImages/H/HamptonConventionVisitorBureau/Grandview_Nature_Preserve.jpg?width=300&height=200&scale=upscalecanvas" /></label><div class="imgbox"><input type="checkbox" checked="checked" id="img2" name="img2" value="0"  /><p class="imgtext">Dramatics Society</p></div></div>
        <div class="col-md-2 col-sm-4 col-xs-6"><label for="img3"><img class="img-responsive" src="http://blog.arborday.org/wp-content/uploads/2013/02/NEC1-300x200.jpg" /></label><div class="imgbox"><input type="checkbox" checked="checked" id="img3" name="img3" value="0"  /><p class="imgtext">Dance Society</p></div></div>
       
        <div class="col-md-2 col-sm-4 col-xs-6"><label for="img6"><img class="img-responsive" src="http://th03.deviantart.net/fs70/200H/f/2010/256/0/9/painting_of_nature_by_dhikagraph-d2ynalq.jpg" /></label><div class="imgbox"><input type="checkbox" checked="checked" id="img6" name="img6" value="0"  /><p class="imgtext">Web Design</p></div></div>
	    <div class="col-md-2 col-sm-4 col-xs-6"><label for="img7"><img class="img-responsive" src="http://2.bp.blogspot.com/-H6MAoWN-UIE/TuRwLbHRSWI/AAAAAAAABBk/89iiEulVsyg/s400/Free%2BNature%2BPhoto.jpg" /></label><div class="imgbox"><input type="checkbox" checked="checked" id="img7" name="img7" value="0"  /><p class="imgtext">Entrepreneurship</p></div></div>
        <div class="col-md-2 col-sm-4 col-xs-6"><label for="img8"><img class="img-responsive" src="http://blog.arborday.org/wp-content/uploads/2013/02/NEC1-300x200.jpg" /></label><div class="imgbox"><input type="checkbox" checked="checked" id="img8" name="img8" value="0"  /></div></div>
     <%=submit_tag "Join groups and have fun!",class:"btn btn-primary btn-lg" %>
     <% end %>
    </div>
   
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="list-group">
  <a href="<%= sort_path(:num => 0)%>" class="list-group-item">
    Today
  </a>
  <a href="<%=sort_path(:num => 1)%>" class="list-group-item">Tomorrow
  </a>
  <a href="<%=sort_path(:week => 7)%>" class="list-group-item">This Week
  </a>
  <a href="<%=sort_path(:month => 7)%>" class="list-group-item">This Month
  </a>
 
</div>
<div class="well">
<legend><div class="tour_8"></div>Filter by Date</legend>
<%= form_tag sort_path, :method => :get, class:"form-horizontal" do %>
 <%= select_date(Date.current, {order: [:day, :month, :year]}, {:class=>"form-control"}) %>
<%=submit_tag ">", class: "btn btn-primary btn-sm"%>

   <% end %>

   </div>
   <div class="well">
<legend>Filter by </legend>
<%= form_tag refresh_path, :method => :get do %>
<div class="form-group">
   <%= select("category", "category_id",Category.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Type'},{class: "form-control"}) %>
   
   <%= select("domain", "domain_id", Domain.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Topic'},{class: "form-control"}) %>
   
   <%= select("eligible", "eligible_id", Eligible.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Eligibility'},{class: "form-control"}) %>
   
   <%=submit_tag "Filter", class: "btn btn-primary btn-sm"%>
   <% end %> 
   </div>
   </div>
</div>

app/views/shared/_signup_form.html.erb
<%= form_for @user do |f| %>
          <%= render 'shared/error_messages', :object => f.object %>     
          <%= f.text_field :email, :placeholder =>'Email',class: 'form-control' %>
          <%= f.password_field :password, :placeholder =>'Password',class: 'form-control'%><br>
          <%= f.hidden_field :name, value:"New-Bee", readonly: "readonly" %>
          <%= f.collection_select :campus, Campus.all, :id, :name,{:prompt => 'Please select your campus'},{class: "form-control"} %>
          <%= f.hidden_field :role,class: 'form-control', value: "user", readonly: "readonly" %><br>      
          <%= f.submit "Create my account", class: "btn btn-large btn-primary" %> 
  <% end %>
  <% if signed_in?%> 
      <h4>Link Your Accounts</h4>
      <% else %><br> 
      <h4>Social logins </h4>
      <% end %>
     <div id="social">
      <div class="social-icons-row" >
        <% if @auth.where('provider'=>'facebook').present?%>             
          <a href="#" target="_blank" style="color: blue;"><i class="icon-facebook"></i></a>
            <% else %>
             <a href="<%=user_omniauth_authorize_path(:facebook)%>" target="_blank"><i class="icon-facebook"></i></a>
         <% end %>
         <% if @auth.where('provider'=>'google_oauth2').present?%>
            <a href="#" target="_blank" style="color: orange;"><i class="icon-google-plus"></i></a>
              <% else %>
               <a href="<%=user_omniauth_authorize_path(:google_oauth2)%>" target="_blank"><i class="icon-google-plus"></i></a> 
          <% end %>
          <% if @auth.where('provider'=>'twitter').present?%>
            <a href="#" target="_blank" style="color: skyblue;"><i class="icon-twitter"></i></a>
              <% else %>
               <a href="<%=user_omniauth_authorize_path(:twitter)%>" target="_blank"><i class="icon-twitter"></i></a>
          <% end %>
         </div>
       </div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_video.html.erb
<iframe width="490" height="275" src="http://www.youtube.com/embed/j4GU0wNGRIo" frameborder="0" allowfullscreen></iframe>