config/routes.rb
NkV1::Application.routes.draw do

 root 'static_pages#launch'
 get "/demo" => "static_pages#home", via: "get"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
   mount Ckeditor::Engine => '/ckeditor'
   if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end
   resources :contact_forms
 devise_for :users , :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'} 
 match '/del_google_calendar_alert', to:'set_alerts#remove_google_calendar_alert', via: 'get'
 match '/del_fb_alert', to:'set_alerts#remove_fb_alert', via: 'delete'
 match '/set_fb_alert', to:'set_alerts#set_fb_alert', via: 'get'
 match '/set_google_calendar_alert', to:'set_alerts#set_google_calendar_alert', via: 'get'
 match '/refresh', to:'refresh#index', via: 'get'
 match '/delfb', to:'push2fb#destroy', via: 'delete'       
 match '/sort', to:'refresh#by_date', via:'get' 
 match '/search', to:'refresh#search', via:'get' 
 match '/myevents', to:'refresh#myevents', via:'get'
 match '/hall', to:'refresh#hallevents', via:'get'
 match '/campus', to:'refresh#campusevents', via:'get'
 match '/approvals', to:'admin#index', via:'get' 
 match '/approve', to:'admin#update', via:'get'                        
 get "users/preferences"

   resources :events do #, shallow: true
      put :favorite, on: :member
        put :followfeed, on: :member
          put :share, on: :member
            put :submit, on: :member
   end
   
   resources :groups, except: [:show, :index]
   resources :campuses do
       resources :groups, only: [:show, :index]      
   end
   resources :users do
     member do
       get :following, :followers
     end
   end
   resources :microposts, :only => [:create, :destroy]
   resources :relationships, :only => [:create, :destroy]

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/new_events', to: 'static_pages#new_events', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/our_works', to: 'static_pages#our_works', via: 'get'
  match '/patnerships', to: 'static_pages#patnerships', via: 'get'
  
end

app/models/event.rb
require 'elasticsearch/model'
class Event < ActiveRecord::Base
include Elasticsearch::Model
#attr_accessor :upload, :edate, :contact_phone 
 extend FriendlyId 
  attr_accessible :title,:organizer,:sdatetime,:edatetime,:contact_name,
                  :contact_phone, :email,:short_description,:events_description,
                  :venue, :user_id, :avatar,:category_ids,:domain_ids, 
                  :eligible_ids,:favorites, :shares, :web, :reach_id,
                  :workflow_state, :slug, :campus_id, :group
  friendly_id :title, use: :slugged                               
#----------------------Namescopes----------------------------#
  scope :approved, lambda{ where(:workflow_state => "accept")}
    scope :rejected, lambda{ where(:workflow_state => "reject")}
      scope :latest, lambda{ order("events.updated_at DESC")}
        scope :search, lambda{|query| where(["lower(title) LIKE ?", "%#{query.downcase}%"])}
         scope :upcoming, lambda{ where("edatetime > ?", Time.now)}

#----------------------Validations----------------------------#
validates :title, :presence => true, length: {maximum: 50}
validates_datetime :sdatetime, :after => Time.now + 45.minutes 
validates_datetime :edatetime, :after => :sdatetime
validates :organizer, :presence => true
validates :venue, :presence => true
validates :reach, :presence => true
validates :campus, :presence => true
validates :events_description, :presence => true
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
validates :short_description, :presence => true, :length => { :maximum => 140}
VALID_PHONE = /([0]|\+91)?[789]\d{9}/
validates :web,:allow_blank => true, :format => URI::regexp(%w(http https)) 
validates :contact_phone, :presence => true, format: { with: VALID_PHONE }
has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
                                :default_url => "/images/:style/missing.png"
                           

validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
validates_attachment :avatar, :size => { :in => 0..150.kilobytes },
                     :content_type => { :content_type => ["image/jpg", "image/gif", "image/png","image/jpeg"] }
#----------------------End----------------------------#
#----------------------Relationships----------------------------#
#validates :user_id, :presence => true
has_many :set_alerts, :dependent => :destroy
has_many :favorites, :dependent => :destroy
has_many :shares, :dependent => :destroy
has_many :followfeeds, :dependent => :destroy
has_and_belongs_to_many :categories
has_and_belongs_to_many :domains
has_and_belongs_to_many :eligibles
has_many :favorited_by, through: :favorites, source: :user
has_many :shared_by, through: :shares, source: :user
has_many :followfeeds_by, through: :followfeeds, source: :user
belongs_to :user
belongs_to :reach
belongs_to :campus
belongs_to :group
#----------------------End----------------------------#
include Workflow
  workflow do
    state :new do
      event :submit, :transitions_to => :being_reviewed
    end
    state :being_reviewed do
      event :accept, :transitions_to => :accepted
      event :reject, :transitions_to => :rejected
    end
    state :accepted
    state :rejected
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :save_event, only: [:create]
before_action :authenticate_user!, except: [:new, :show, :index ]  #:only: [:new, :create ,:blah]
 def show
   
   @event = Event.friendly.find(params[:id])
   @category=@event.categories
   @domain = @event.domains
   @eligible=@event.eligibles
   @user = current_user || User.new
   
  end

  # GET /events
  # GET /events.json
  def index
  @user = current_user || User.new
    @events = Event.approved
    @events = @events.paginate :page => params[:page], :per_page => 10
      respond_to do |format|
        format.html
        format.atom
      end
  end

  # GET /events/1
  # GET /events/1.json
# before_filter :authenticate_user!
  # GET /events/new
  def new
   if session[:events].present?
     @event = Event.new
      @event.attributes = session[:events]
   else
      @event = Event.new
   end
  end

  # GET /events/1/edit
  def edit 
     @event = Event.friendly.find(params[:id])
     authorize! :edit, @event
   end

  # POST /events
  # POST /events.json
 def create
  if session[:events].present?
    @event = Event.new
     @event.attributes = session[:events]  
      #reset_session
       session.delete(:events)
     else
    @event = Event.new(event_params)
   end
     @event.user_id = current_user.id
       respond_to do |format|
      if @event.save
            
     # debugger
        format.html { redirect_to @event, notice: 'Event submitted for review.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
   
       
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
 def update

  @event = Event.friendly.find(params[:id]) 
  authorize! :edit, @event
    respond_to do |format|
      if @event.update_attributes(event_params)
       
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def submit
    @event = Event.friendly.find(params[:id])
    @event.update_column(:workflow_state,"submit")
    redirect_to @event, notice: "Submitted for approval"
  end
  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.friendly.find(params[:id])
    authorize! :edit, @event
    if @event.present?
    @event.destroy
    end
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
    
 def favorite
 @event = Event.friendly.find(params[:id])
    type = params[:type]
    if type == "favorite"
      current_user.userfavorites << @event
      redirect_to :back, notice: "You favorited #{@event.title}"

    elsif type == "unfavorite"
      current_user.userfavorites.delete(@event)
      redirect_to :back, notice: "Unfavorited #{@event.title}"

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end
  
  def share
 @event = Event.friendly.find(params[:id])
    type = params[:type]
    if type == "share"
      current_user.usershares << @event
      redirect_to :back, notice: "You promoted the event #{@event.title}"

    elsif type == "undo share"
      current_user.usershares.delete(@event)
      redirect_to :back, notice: "Undo promote #{@event.title}"

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end
  
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
  def save_event
  @event = Event.new(event_params)
    session[:events]=@event.attributes
  end


    def event_params
      params.require(:event).permit(:email,:contact_name,:title,:sdatetime,:venue,
      :location,:events_description,:short_description,:email,:user,:organizer,
      :edatetime,:contact_phone,{:domain_ids =>[]},{:category_ids =>[]},
      {:eligible_ids =>[]},:avatar,:web,:reach,:workflow_state,
      :slug,:campus, :group)                              
    end  
  

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :college %><br>
    <%= f.text_field :college %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<title></title>	

     <%= stylesheet_link_tag "jquery.datetimepicker.css" %>	
     <%= javascript_include_tag "jquery.datetimepicker.js" %>
                  <%= javascript_include_tag "test.js" %>
                  				
      <div class="container" style="width:1170px">	
      <!-- END SIDEBAR -->
      
        <ul class="breadcrumb">
            <li> <i class="icon-home"></i> <a href="#">Home</a> 
            <span class="divider">/</span> </li>
            <li><a href="#">Events</a> <span class="divider">/</span></li>
            <li>Add Event</li>
          </ul>

              <div class="well">
                  <%= form_for @event,:html => {:novalidate =>'novalidate'} do |u| %>
                  <fieldset>                
                  <span class="label label-primary">Edit Details</span>
                   <span class="label label-default">Preview</span>
                  <span class="label label-default">Submit for Moderation</span>
                  <span class="label label-default">Pending for Moderation</span>
                  <legend><h3>Event Edit Form</h3>
                   </legend>
                  <%= render 'shared/error_messages', :object => u.object %>  
             <br>
             <br>
             <div class="row">
              <div class="col-lg-6">
                    <div id="form-group"> 
                      <!--Competition Title-->
                
               <label class="col-lg-3 control-label">Event Title</label>
                        
                        <div class="col-lg-9">
<%= u.text_field :title, autocomplete: 'off',class: 'form-control' %>
             
                        </div>
                       </div>        
                      <!--Festivals-->
                <!----      <div id="form-group">                  
                          <label class="col-lg-3 control-label">Festival <span>(If any)</span></label>
                      <div class="col-lg-9">
                         <input validateon="blur" autocomplete="off" class="form-control" id="url" name="url" tabindex="2" type="text">
   </div>
   </div>
   
                      <!--Organizers-->
                       <div id="form-group">
                          <label class="col-lg-3 control-label">Organizer</label>
                     <div class="col-lg-9">
                        
                          <%= u.text_field :organizer, autocomplete: 'off',class: 'form-control' %>
                        </div>
                      
                      </div>
                      
                      <!--Website URL-->
                     
                      <div id="form-group">
                          <label class="col-lg-3 control-label">Venue</label>
                     <div class="col-lg-9">
                        
                          <%= u.text_field :venue, autocomplete: 'off',class: 'form-control',:placeholder => 'Building,room no. etc.' %>
                        </div>
                      
                      </div>
   <div id="form-group">
                         
            <label class="col-lg-3 control-label">Location</label>
                        <div class="col-lg-9">
                          <%= u.text_field :location, autocomplete: 'off',class: 'form-control',:placeholder => 'place'  %>
                        </div>
                      </div> 
                      <!--Start date and end date-->
                      <div id="form-group">
                         
                          <label class="col-lg-3 control-label">Event From To</label>
                       <div class="col-lg-9">
                 <%= u.datetime_select :sdatetime, class: 'form-control'%> 
                 <%= u.datetime_select :edatetime,class: 'form-control'%>  
                        </div>
                        
                        </div>
                        
                         <div id="form-group">          <label class="col-lg-3 control-label">Website</label>
                   <div class="col-lg-9">
                         <%= u.url_field :web,class: 'form-control' %>
                        </div>
                     
                      </div>
                      
                  <div id="form-group">
                         
             <label class="col-lg-3 control-label">Short Event Description</label>
                        <div class="col-lg-9">
                 <%= u.text_area :short_description,class: 'form-control',placeholder: "max. 140 characters" %>   <div id='counter'>140</div>
                        </div>
                        </div>
                        <div id="form-group">
                         
                          <label for="url" class="col-lg-3 control-label">Contact Details</label>
                        <div class="col-lg-9 widthLong">
                        <%= u.text_field :contact_name,class: 'form-control',placeholder: 'Name' %>
                        <%= u.text_field :contact_phone,class: 'form-control',placeholder: 'mobile no.' %>
                        <%= u.email_field :email,class: 'form-control',placeholder:'Email Id' %>
                          </div>
                        </div> 
                         
                         <div id="form-group">
                         
                          <label for="url" class="col-lg-3 control-label">Region</label>
                    
                        <div class="col-lg-9">
                          <label style="float:left;padding:8px 20px 8px 0;font-size:14px;" class="col-lg-3 control-label" >
                            <input name="region" value="india" id="region_india" checked="checked" tabindex="2" type="radio">
                            India</label>
                          
                           
                        </div>
                    
                      </div>
                      <div id="form-group">
                         
                          <label class="col-lg-3 control-label">Event Logo</label>
                        <div class="col-lg-9">
                        <%= u.file_field :avatar %> 
                      </div>
                      </div>
                      </div>
                      <!--Location-->
                      
                <div class="col-lg-6">       
                          
                      <!--Domains--><div id="form-group">
                         <br>
                          <label class="col-lg-3 control-label">Event Reach</label>
                       
                        <div class="col-lg-9">
         <%= u.collection_select(:reach_id, Reach.all, :id, :name,include_blank: true) do |b|
                          b.label(class:"btn btn-default category") { b.check_box(class: "hide") + b.text } end %>  
                        </div>
                        
                      </div>
                     <br>
                      
                      <div id="form-group">
                         <br>
                          <label class="col-lg-2 control-label">Domains</label>
                       
                        <div class="col-lg-10">
       <%= u.collection_check_boxes(:domain_ids, Domain.all, :id, :name) do |b|
          b.label(class:"btn btn-default category") { b.check_box(class: "hide") + b.text }
                        end %>
      <%=link_to"Add a new Domain",rails_admin.new_path('Domain'),target: '_blank' %>                       
                        </div>
                        
                      </div>
                     <br>
                      <!--Categories-->
                      <div id="form-group">
                      <br>
                          <label class="col-lg-2 control-label">Categories</label>
                        <div class="col-lg-10">
               <%= u.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b|
                          b.label(class:"btn btn-default category") { b.check_box(class: "hide") + b.text }
                        end %>
<%=link_to"Add a new Category",rails_admin.new_path('Category'),target: '_blank' %>                       
                        </div>
                      </div>
                      <br>
                      <!--Eligibility-->
                      <div id="form-group">
                         <br>
                          <label class="col-lg-2 control-label">Eligibility</label>
                        <div class="col-lg-10">
                        <%= u.collection_check_boxes(:eligible_ids, Eligible.all, :id, :name) do |b|
                          b.label(class:"btn btn-default category") { b.check_box(class: "hide") + b.text }
                        end %>
 <%=link_to"Add a new Eligible Criteria",rails_admin.new_path('Eligible'),target: '_blank' %>
                        <br>
                       </div>                                                
                      </div>
			</div>	
			  
                       <!--Competitions Registration URL-->
 
                      <!--Competitions Details-->
                     
                    <div class ="col-lg-9">
                     <div id="form-group">
                         
                          <label class="col-lg-2 control-label">Event Details<br>(For Event Page)</label>
                          
                        <div class="col-lg-10">
                          <%= u.cktext_area :events_description, :class => 'ckeditor',style: 'width: 80%;height: 200px' %>
                          
                        </div>  
                      </div>
                      </div>
                      <div class="col-lg-3">
                      <br>
                      <br><br>
                      <%=u.submit 'Submit Event', class:'btn btn-primary btn-md',type: 'submit' %><br>
                      <%=u.submit'Cancel', class:'btn btn-danger btn-md',type: 'reset' %> 
                      </div>
                      </div>
                      
                       </div> 
                      
                      <!--Attachments-->
                      
                      <!--Deadlines-->
                        
                      </div>                    
                     </fieldset>   
                  <% end %>
                  </div>
      
                </div>
                </div>
                </div>
              <script type="text/javascript" language="javascript" charset="utf-8">
                        $("input[id*='event_domain_ids'],input[id*='event_category_ids'],input[id*='event_eligible_ids']").each(function(){
                                if($(this).prop('checked')){
                                        $(this).parent().removeClass('btn-default');
                                        $(this).parent().addClass('btn-info');
                                }
                        });                </script>
                        <script type="text/javascript" language="javascript" charset="utf-8">
   (function($){$.fn.limiter=function(options){var that=this;options=$.extend({limit:140,counter:$('#counter')},options);var count=function(value,e){var total=options.limit-value.length;if(total>=0){options.counter.text(total)}else{if(e.type=='keypress'){e.preventDefault()}}};return that.each(function(){$(that).on('keypress keyup',function(evt){count($(that).val(),evt)})})}})(jQuery);$('#event_short_description').limiter();
                        </script>

app/views/events/index.html.erb
<title></title> 
      <div class="container">
      <br>
<br>
       <div class="row">
       <div class="col-lg-2">
    <br>

  
    <div class="list-group">
  <a href="<%= sort_path(:num => 0)%>" class="list-group-item">
    Today
  </a>
  <a href="<%=sort_path(:num => 1)%>" class="list-group-item">Tomorrow
  </a>
  <a href="<%=sort_path(:week => 7)%>" class="list-group-item">This Week
  </a>
  <a href="<%=sort_path(:month => 7)%>" class="list-group-item active">This Month
  </a>
 
</div>
<div class="well">
<legend>Filter by Date</legend>
<%= form_tag sort_path, :method => :get do %>
 <%= select_date(date = Date.current, {order: [:day, :month, :year]}, {:class=>"form-control"}) %>
<%=submit_tag ">", class: "btn btn-primary btn-sm" %>

   <% end %>

   </div>
   <div class="well">
<legend>Filter by </legend>
<%= form_tag refresh_path, :method => :get do %>
<div class="form-group">
   <%= select("category", "category_id",Category.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Fill Category'},{class: "form-control"}) %>
   
   <%= select("domain", "domain_id", Domain.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Fill Domain'},{class: "form-control"}) %>
   
   <%= select("eligible", "eligible_id", Eligible.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Fill Eligible'},{class: "form-control"}) %>
   
   <%=submit_tag "Search"%>
   <% end %> 
    </div>
    </div>
   </div>
<div class="col-lg-10">
        <div class="page-header">
          <h1>All Events</h1>
        </div>
        <%= render partial: "static_pages/event", collection: @events %> 
        
<%= will_paginate @events, class:"pager" %>
    <%= button_to 'Add an Event', new_event_path, method: 'get', class: "btn btn-primary btn-sm" %>
    <!-- End: MAIN CONTENT -->
    <!-- Start: FOOTER -->
    </div>
    </div>
    </div> 
     <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <script type="text/javascript" language="javascript" charset="utf-8">
   // <![CDATA[
          $('[data-toggle="popover"]').popover({trigger: 'hover'});
   // ]]>
   </script> 
    

app/views/events/show.html.erb
<title></title>
<div id="fb-root"></div>
<% content_for :javascripts do %>
<script type='text/javascript'>
    handler = Gmaps.build('Google');
    /* rest of maps building JS */
</script>
<% end %>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=235140026659021";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

           <div class="container">
                              
                         <div class="cover">                                               
                    <legend><h2><%= @event.title %></h2>
                     <p><a class="label label-primary">Bee Score: <%= @event.shared_by.count%></a>
                    <% if @user.usershares.include?(@event) %>
        <%= link_to share_event_path(@event, type: "undo share"), method: :put ,:class => "btn btn-primary btn-xs tour_3" do %><i class="icon icon-share">Un-bee it!</i>
        <% end %>
        <% else %>
       
        <%= link_to share_event_path(@event, type: "share"), method: :put,:class => "btn btn-primary btn-xs" do %><i class="icon icon-share">Bee it!</i> 
        <% end %>
    <% end %>
    </p>     </legend>
                    
                    </div>
                          <div class="row">
                          <div class="col-lg-6">
                          
                          <div class="thumbnail">
                            <%if @event.avatar.present?%>
        <%= image_tag @event.avatar.url, size: "300x200"%>
        <% else %>
        <%= image_tag 'logo1.png', size: "300x200"%>
       <% end %>
      
               </div>
                          </div>
                          <div class="col-lg-6">
                          
                         
	         <i class="fa fa-calendar"></i> <%=@event.sdatetime.strftime("%B %d,%Y %I:%M %p")%> - <%=@event.edatetime.strftime("%B %d,%Y %I:%M %p")%>
	         <h4><i class="fa fa-users"></i> <%= @event.organizer %></h4>					
		<i class="icon icon-map-marker"> </i>
    <%=@event.venue%>,<%=@event.location%>		
				
		<br>
		<br>	
			
                         <i class="fa fa-tags"></i> <% @category.each do |u|%>
                                 <span class="label label-warning"><%= u.name%></span>
                                 <% end %> 
                                 <% @domain.each do |u|%>
                                 <span class="label label-primary"><%= u.name%></span>
                                 <% end %> 
                                 <% @eligible.each do |u|%>
                                 <span class="label label-primary opac"><%= u.name%></span>
                                 <% end %> <br><br><br>
                           <b>Short Description</b>
                        
                        <%=@event.short_description %> 
                        
                         
                          </div>
                          
                          </div>
                         
                          
                          
                          <legend>Event Description</legend>
                          <div class= "row">
                         <div class="col-lg-8">
                         
                           
                    <%=raw@event.events_description %> 
                    </div>
                         <div class="col-lg-4">
                          
                          <table class="table ">
                           <b>EVENT CONTACTS</b>
                          <tbody>
                            <tr>
                            <td>Name:</td><td><%=@event.contact_name%></td>
                            </tr>
                            <tr>
                            <td>mail-to:</td><td><%=@event.email %></td>
                            </tr>
                            <tr>
                            <td>mob:</td><td><%=@event.contact_phone %></td>
                            </tr>
              <td>website:</td><td><a href="<%= @event.web %>" target="_blank"><%= @event.web %></a></td>
                            </tr>
                            </tbody>
                            </table>
                          </div>
                        <div class="col-lg-5">
                        
                        </div>
                        </div>
                         
                     
                     
                        
                  
                  <% if @user.events.include?(@event)%> 
                <!% if can? :edit, Event, %>                                     
                 <%= link_to "Edit Event",edit_event_path, :action=>'edit',:type => 'button',:class => 'btn btn-primary opac'%>  
                 <!%end%>
                 <%= link_to "Submit for approval",submit_event_path, :action=>'edit',:type => 'button',method: :put, :class => 'btn btn-primary'%>    <% end %>
                 <button class="btn btn-warning"><i class="icon-plus icon-white"></i> Add New Event</button>
                 <div style='width: 800px;'>
    <div id="geolocation" style='width: 800px; height: 400px;'></div>
  </div>
                 <div class="fb-comments" data-href="http://kampusbee.com/comments" data-numposts="5" data-colorscheme="dark"></div>
                   </div>
                                       
                
                
               
                 </div>