config/routes.rb
NkV1::Application.routes.draw do

 root 'static_pages#launch'
 get "/demo" => "static_pages#home", via: "get"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
   mount Ckeditor::Engine => '/ckeditor'
   if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
   end
   resources :contact_forms
 devise_for :users , :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'} 
 match '/del_google_calendar_alert', to:'set_alerts#remove_google_calendar_alert', via: 'get'
 match '/del_fb_alert', to:'set_alerts#remove_fb_alert', via: 'delete'
 match '/set_fb_alert', to:'set_alerts#set_fb_alert', via: 'get'
 match '/set_google_calendar_alert', to:'set_alerts#set_google_calendar_alert', via: 'get'
 match '/refresh', to:'refresh#index', via: 'get'
 match '/delfb', to:'push2fb#destroy', via: 'delete'       
 match '/sort', to:'refresh#by_date', via:'get' 
 match '/search', to:'refresh#search', via:'get' 
 match '/myevents', to:'refresh#myevents', via:'get'
 match '/hall', to:'refresh#hallevents', via:'get'
 match '/campus', to:'refresh#campusevents', via:'get'
 match '/approvals', to:'admin#index', via:'get' 
 match '/approve', to:'admin#update', via:'get'                        
 get "users/preferences"

   resources :events do #, shallow: true
      put :favorite, on: :member
        put :followfeed, on: :member
          put :share, on: :member
            put :submit, on: :member
   end
   
   resources :groups, except: [:show, :index]
   resources :campuses do
       resources :groups, only: [:show, :index]      
   end
   resources :users do
     member do
       get :following, :followers
     end
   end
   resources :microposts, :only => [:create, :destroy]
   resources :relationships, :only => [:create, :destroy]

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/new_events', to: 'static_pages#new_events', via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/team', to: 'static_pages#team', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/our_works', to: 'static_pages#our_works', via: 'get'
  match '/patnerships', to: 'static_pages#patnerships', via: 'get'
  
end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49270049-1', 'kampusbee.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.erb
     <title></title>
    <footer>
    <div class="navbar navbar-default footdark">
      <div class="container">
        <div class="row">
          
          <div class="col-lg-3">
            <h4><i class="icon-beaker icon-white"></i> About<h4>
            
              <ul class="quick-links">
                <li><a href="<%=about_path%>">About Us</a></li>
                <li><a href="<%=patnerships_path%>">Patnerships</a></li>
                <li><a href="<%=team_path%>">Team</a></li>
                <li><a href="#">Take a Tour</a></li>
              <ul>
                      
          </div>
          <div class="col-lg-3">
            <h4><i class="icon-thumbs-up icon-white"></i> Support</h4>
            
              <ul class="quick-links">
                <li><a href="<%=faq_path%>">FAQ</a></li>
                <li><a href="<%=new_contact_form_path%>">Contact us</a></li>            
              </ul>
            
         <!---   <i class="icon-legal icon-white"></i> Legal
            
              <ul class="quick-links">
                <li><a href="#">License</a></li>
                <li><a href="#">Terms of Use</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Security</a></li>      
              </ul>----->
                      
          </div>
          <div class="col-lg-3">
            <h4>Get in touch</h4>
            <div class="social-icons-row">
              <a href="https://twitter.com/kampusbee"><i class="icon-twitter"></i></a>
              <a href="https://www.facebook.com/pages/Kampusbeecom/620695481313043?fref=ts"><i class="icon-facebook"></i></a>
              <a href="#"><i class="icon-google-plus"></i></a>             <a href="mailto:kampusbee@gmail.com"><i class="icon-envelope"></i></a>                            
            </div>
            
            <div class="social-icons-row">
              <i class="icon-phone icon-large phone-number"></i> +918884056308
            </div>
          </div>      
          <div class="col-lg-3">
           <!--- <h4>Get updated by email</h4>
            <form>
              <input type="text" name="email" placeholder="Email address">
              <input type="submit" class="btn btn-primary" value="Subscribe">
            </form>--->
          </div>
        </div>
      </div>
      <hr class="footer-divider">
      <div class="container">
        <p>
          &copy; 2014 Kampusbee.com, Inc. All Rights Reserved.
        </p>
      </div>
      </div>
    </footer>
    <!-- End: FOOTER -->

app/views/layouts/_header.html.erb
 <title></title>
    
 <header>
      <!-- Start: Navigation wrapper -->
      <div class="navbar navbar-default navbar-fixed-top dark">
      <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="<%= demo_path %>">Kampusbee.com </a>
       <!----     <div class="logo">
            <%= image_tag 'logo1.png', size: "130x60"%>
            </div>
            <!-- Below button used for responsive navigation -->
  <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
           </div> 
            <div class="navbar-collapse collapse navbar-responsive-collapse">
            <!-- Start: Primary navigation -->
                
              <ul class="nav navbar-nav navbar-right">
            
              
                    <li class="dropdown">
                   
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">About <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="<%=about_path%>">About Us</a></li>
                        <li><a href="<%=patnerships_path%>">Partnerships</a></li>
                        <li><a href="<%=team_path%>">Team</a></li>
                        <li class="divider"></li>
                    
                      </ul>
                      
                    </li>
                     <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Events <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="<%= new_event_path %>">Add Events</a></li>
                        <li><a href="<%= myevents_path %>">My Events</a></li>
                        <li><a href="<%= hall_path %>">Hall Events</a></li>
                        <li><a href="<%= campus_path %>">Campus Events</a></li>
                        <li><a href="<%= events_path%>">All Events</a></li>
                        <li class="divider"></li>
             
                      </ul>
                     
                    </li>
                    <!--
                    <li><a href="<%= faq_path %>">FAQ</a></li>
                    <li><a href="<%= contact_path %>">Contact Us</a></li>----->
                  <% if user_signed_in? %>
 
              <% if current_user.has_role? :superadmin %>
            <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
                  <ul class="dropdown-menu">
            <li><%= link_to "Rails Admin", rails_admin_path %></li>
            <li><%= link_to "Approvals", approvals_path %></li>
            </ul> 
            </li>
             <% end %>          
             	  <li class="dropdown">
             	  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.name%> | Account<b class="caret"></b></a>
                  <ul class="dropdown-menu">                  
         <li><%= link_to "All Users",users_path %></li>
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "User Settings", edit_user_path(current_user) %></li> 
                  <li><%= link_to "Preferences", users_preferences_path %></li>  
                  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>     
         </ul>  
         </li>           
         <% else %>      
                <li><%= link_to "Log in", new_user_session_path %></li> 
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                </ul>
                </li>
          <% end %>
              <div class="navbar-form navbar-right">
  <%= form_tag search_path, :method => :get do %>
        
           
                <%= text_field_tag :search, nil, placeholder: 'Search',class:"form-control col-lg-8" %>
               
                              
                 
             
        
   <% end %> 
 </div>    
                  
                  
            </div>
            </div>
                    
      <!-- End: Navigation wrapper -->   
    </header>
    
    <!-- End: HEADER -->

app/views/layouts/_shim.html.erb
 <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->

<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Kampusbee.com | Stay informed! ">
    <meta name="author" content="Narendra">
    <title>kampusbee.com</title>
    <!-- Bootstrap -->
     <%= stylesheet_link_tag  "application" %>    
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= yield :javascripts %>
    
    <%= csrf_meta_tags %>
          
<%= render 'layouts/shim' %>
<%= render 'layouts/analytics' %>
</head>
<body>

 <div class="bodyfont">      
<div id="bbbb">
  <a href="<%=root_path%>"><%= image_tag 'beta.png'%></a>
</div> 
 <div id="feedback">
   <p class="tour_10"></p>
     <a href="<%=new_contact_form_path%>">Feedback</a>
</div> 

<!---
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=235140026659021";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script> --->

 <%= render 'layouts/header' %> 
<%= render partial: "shared/flash_messages", flash: flash %>

   <%= yield %>
   <a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left"><span class="glyphicon glyphicon-chevron-up"></span></a>
    <script type="text/javascript" language="javascript" charset="utf-8">
   // <![CDATA[
          $('[data-toggle="popover"]').popover({trigger: 'hover'});
   // ]]>
   </script> 
   <%= render 'layouts/footer' %> 
 </div>

  </body>
 
</html>